### ISSUE TITLE
Bug: UserPooldParameter and UserPoolClientIdParameter in backend stack do not update on change

### ISSUE THREAD

**Issue by lmammino** [awsbites/weshare.click#15]
In `backend/serverless.yml` we currently define the following parameter:

```yml
resources:
  Parameters:
    UserPoolIdParameter:
      Type: AWS::SSM::Parameter::Value<String>
      Default: /weshare/${sls:stage}/userPoolId
    UserPoolClientIdParameter:
      Type: AWS::SSM::Parameter::Value<String>
      Default: /weshare/${sls:stage}/userPoolClientId
```

These parameters are only populated at the first deployment and are not kept up to date anymore.

If a user redeploys the user pool for any reason, these parameters should change and the backend stack should be able to reference the new values.

This will result in a permanently failed authentication and the inability to upload files.

A possible solution might be to not rely on CloudFormation parameters but use SSM values directly.

A current workaround is to manually update the API Gateway Authorizer for the createShare endpoint and specify there the new values.
